syntax = "proto3";

option java_package = "com.example.rideshare.grpc";
option java_multiple_files = true;

package rideadditions;

service RideAddition {
    rpc AdditionRide (AnalyzeRideRequest) returns (RideAnalysisResponse);
}

message AnalyzeRideRequest {
    string  ride_id        = 1;
    string departure_city = 2;
    string arrival_city   = 3;
    int32  price_declared = 4;
    string departure_time = 5;
    int32  total_seats    = 6;
}

message RideAnalysisResponse {
    string  ride_id               = 1;
    int32  estimated_distance_km = 2;
    int32  recommended_price     = 3;
    string price_deviation       = 4;
    string route_difficulty      = 5;
}