spring:
  application:
    name: audit-service

    # ??????????? ? ?????????? ???????
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    #  Spring Boot ???????? trace-id ?? AMQP-?????????? ? MDC ???????.
    # ??? ????????? ??????? ?????? ? demo-rest ? ?????????? ? audit-service.
    listener:
      simple:
        observation-enabled: true
        # ??? ?????? ????????? ????????? 3 ???? ? ?????????? 2 ???????.
        # ????? ?????????? ??????? ????????? ?????? ? DLQ (????????? ? RabbitMQConfig).
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2.0

    template:
      observation-enabled: true

# audit-service ???????? ?? ?????? ?????, ????? ?? ????????????? ? demo-rest (8080)
server:
  port: 8081

# Health endpoint ?????????? ????????? ??????????? ? RabbitMQ.
# ? ???? ???????? ??? ???????????? ??? readiness-???????? ? Kubernetes.
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

