spring.application.name=rideshare-rest-graphQL

spring.graphql.graphiql.enabled=true

spring.graphql.path=/graphql

spring.graphql.schema.locations=classpath*:graphql/

dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls

spring.graphql.schema.introspection.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:postgresql://localhost:5432/rideshare_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true